global:
  max_iterations: 200
  results_path: "./logs/tmp"
  dt: 0.1

components:
  - plastic

actors:
  production:
    type: SimpleSource
    source: true
    component: plastic
    speed:
      time: 1
      quantity: 14391520
    max_production: 143915200
    delay: 1
    clients:
      use: 
        plastic: 100

  use:
    type: SimpleActor
    component: plastic
    log: 
      plastic:
        constant:
         value: 8.0
    clients: 
      use: 
        plastic: 29
      recycling: 
        plastic: 7
      discard: 
        plastic: 55
      incineration: 
        plastic: 9
  
  recycling:
    type: SimpleActor
    component: plastic
    log: 
      plastic: null
    clients: 
      use: 
        plastic: 100

  discard: 
    type: SimpleSink
    component: plastic

  incineration:
    type: SimpleSink
    component: plastic
